apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/aminammar1/chess-puzzle-next-go/client
    newTag: v1.0.1
  - name: ghcr.io/aminammar1/chess-puzzle-next-go/api-gateway
    newTag: v1.0.1
  - name: ghcr.io/aminammar1/chess-puzzle-next-go/puzzle-generator
    newTag: v1.0.1
  - name: ghcr.io/aminammar1/chess-puzzle-next-go/voice-to-move
    newTag: v1.0.1
