"use client";

import { motion } from "framer-motion";
import type { DifficultyLevel } from "@/lib/types";
import { cn } from "@/lib/utils";

interface DifficultyPickerProps {
  source: "lichess" | "dataset" | "ai";
  onSelect: (difficulty: DifficultyLevel) => void;
  loading?: boolean;
}

const sourceInfo = {
  lichess: {
    icon: "♞",
    title: "Lichess Puzzles",
    subtitle: "Real puzzles from rated Lichess games",
    color: "green",
  },
  dataset: {
    icon: "♜",
    title: "Dataset Puzzles",
    subtitle: "Millions of rated puzzles from the Lichess database",
    color: "blue",
  },
  ai: {
    icon: "♛",
    title: "AI Puzzles",
    subtitle: "Custom puzzles generated by artificial intelligence",
    color: "purple",
  },
};

const difficulties: { level: DifficultyLevel; label: string; rating: string; description: string }[] = [
  { level: "easy", label: "Easy", rating: "< 1300", description: "Basic tactics, simple combinations" },
  { level: "medium", label: "Medium", rating: "1300 – 1800", description: "Multi-move tactics, pins, forks" },
  { level: "hard", label: "Hard", rating: "1800+", description: "Complex combinations, deep calculation" },
];

export default function DifficultyPicker({ source, onSelect, loading }: DifficultyPickerProps) {
  const info = sourceInfo[source];

  return (
    <div className="mx-auto max-w-lg">
      {/* Source Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="mb-10 text-center"
      >
        <div className="mb-4 text-5xl animate-float">{info.icon}</div>
        <h1 className="font-serif text-3xl font-bold text-[var(--text-primary)]">{info.title}</h1>
        <p className="mt-2 text-sm text-[var(--text-muted)]">{info.subtitle}</p>
      </motion.div>

      {/* Difficulty Cards — Glass morphism hover */}
      <div className="space-y-3">
        <p className="text-center font-serif text-sm font-semibold uppercase tracking-[0.15em] text-[var(--text-muted)]">
          Choose Difficulty
        </p>

        {difficulties.map((d, i) => {
          const glassHover = {
            easy: "hover:bg-green-500/[0.08] hover:border-green-500/20 hover:shadow-green-500/5",
            medium: "hover:bg-yellow-500/[0.08] hover:border-yellow-500/20 hover:shadow-yellow-500/5",
            hard: "hover:bg-red-500/[0.08] hover:border-red-500/20 hover:shadow-red-500/5",
          };
          const dotColor = {
            easy: "bg-green-500",
            medium: "bg-yellow-500",
            hard: "bg-red-500",
          };
          const ratingColor = {
            easy: "text-green-400",
            medium: "text-yellow-400",
            hard: "text-red-400",
          };

          return (
            <motion.button
              key={d.level}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              whileHover={{ scale: 1.01 }}
              whileTap={{ scale: 0.99 }}
              onClick={() => onSelect(d.level)}
              disabled={loading}
              className={cn(
                "group flex w-full items-center gap-4 rounded-xl border border-white/[0.06] bg-white/[0.02] backdrop-blur-sm p-5 text-left",
                "shadow-lg shadow-black/10 transition-all duration-300 disabled:opacity-40",
                "hover:shadow-xl hover:backdrop-blur-md",
                glassHover[d.level]
              )}
            >
              <div className={cn("h-3 w-3 rounded-full shadow-lg transition-transform duration-300 group-hover:scale-125", dotColor[d.level])} />
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <h3 className="font-serif text-lg font-semibold text-[var(--text-primary)]">{d.label}</h3>
                  <span className={cn("font-mono text-sm font-bold", ratingColor[d.level])}>{d.rating}</span>
                </div>
                <p className="mt-0.5 text-xs text-[var(--text-muted)]">{d.description}</p>
              </div>
              <span className="text-[var(--text-muted)] transition-all group-hover:translate-x-1 group-hover:text-[var(--text-secondary)]">→</span>
            </motion.button>
          );
        })}
      </div>

      {loading && (
        <div className="mt-8 flex items-center justify-center">
          <div className="text-center">
            <div className="mb-3 text-4xl animate-float">♔</div>
            <p className="font-serif text-sm text-[var(--text-muted)]">Loading puzzle...</p>
            <div className="mx-auto mt-3 h-1 w-24 overflow-hidden rounded-full bg-white/[0.05]">
              <div className="h-full w-1/2 animate-shimmer rounded-full bg-gradient-to-r from-transparent via-[var(--accent-gold)] to-transparent" />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
